// lib/kanji-bank.ts
import type { KanjiEntry } from "@/lib/seal/types";

/**
 * Curated bank of evocative kanji. Themes are advisory (no UI surface in v1)
 * and used by the seed script to ensure variety across consecutive days.
 *
 * Bank size must exceed 365 so the rolling no-repeat window in
 * `lib/seal/calendar.ts` always finds an unused entry.
 *
 * Romaji uses common kun-yomi readings where natural; on-yomi where the
 * kun-yomi is rarely seen. Treat readings as advisory display labels —
 * any reading errors should be corrected before launch by a JP reviewer.
 */
export const KANJI_BANK: KanjiEntry[] = [
  // Original starter set
  { kanji: "月", romaji: "tsuki",  meaning: "moon",     themes: ["sky", "weekday"] },
  { kanji: "火", romaji: "hi",     meaning: "fire",     themes: ["element", "weekday"] },
  { kanji: "水", romaji: "mizu",   meaning: "water",    themes: ["element", "weekday"] },
  { kanji: "木", romaji: "ki",     meaning: "tree",     themes: ["nature", "weekday"] },
  { kanji: "金", romaji: "kane",   meaning: "metal",    themes: ["element", "weekday"] },
  { kanji: "土", romaji: "tsuchi", meaning: "earth",    themes: ["element", "weekday"] },
  { kanji: "日", romaji: "hi",     meaning: "sun",      themes: ["sky", "weekday"] },
  { kanji: "山", romaji: "yama",   meaning: "mountain", themes: ["nature"] },
  { kanji: "川", romaji: "kawa",   meaning: "river",    themes: ["nature"] },
  { kanji: "海", romaji: "umi",    meaning: "sea",      themes: ["nature"] },
  { kanji: "空", romaji: "sora",   meaning: "sky",      themes: ["sky"] },
  { kanji: "雲", romaji: "kumo",   meaning: "cloud",    themes: ["sky"] },
  { kanji: "雨", romaji: "ame",    meaning: "rain",     themes: ["weather"] },
  { kanji: "雪", romaji: "yuki",   meaning: "snow",     themes: ["weather", "winter"] },
  { kanji: "風", romaji: "kaze",   meaning: "wind",     themes: ["weather"] },
  { kanji: "花", romaji: "hana",   meaning: "flower",   themes: ["nature", "spring"] },
  { kanji: "葉", romaji: "ha",     meaning: "leaf",     themes: ["nature"] },
  { kanji: "鳥", romaji: "tori",   meaning: "bird",     themes: ["nature"] },
  { kanji: "石", romaji: "ishi",   meaning: "stone",    themes: ["nature"] },
  { kanji: "光", romaji: "hikari", meaning: "light",    themes: ["abstract"] },
  { kanji: "影", romaji: "kage",   meaning: "shadow",   themes: ["abstract"] },
  { kanji: "朝", romaji: "asa",    meaning: "morning",  themes: ["time"] },
  { kanji: "夜", romaji: "yoru",   meaning: "night",    themes: ["time"] },
  { kanji: "星", romaji: "hoshi",  meaning: "star",     themes: ["sky"] },
  { kanji: "音", romaji: "oto",    meaning: "sound",    themes: ["abstract"] },
  { kanji: "道", romaji: "michi",  meaning: "path",     themes: ["abstract"] },
  { kanji: "心", romaji: "kokoro", meaning: "heart",    themes: ["abstract"] },
  { kanji: "気", romaji: "ki",     meaning: "spirit",   themes: ["abstract"] },
  { kanji: "力", romaji: "chikara",meaning: "strength", themes: ["abstract"] },
  { kanji: "白", romaji: "shiro",  meaning: "white",    themes: ["color"] },
  { kanji: "黒", romaji: "kuro",   meaning: "black",    themes: ["color"] },
  { kanji: "赤", romaji: "aka",    meaning: "red",      themes: ["color"] },
  { kanji: "青", romaji: "ao",     meaning: "blue",     themes: ["color"] },
  { kanji: "古", romaji: "furu",   meaning: "old",      themes: ["abstract"] },
  { kanji: "新", romaji: "atara",  meaning: "new",      themes: ["abstract"] },
  { kanji: "静", romaji: "shizu",  meaning: "quiet",    themes: ["abstract"] },
  { kanji: "動", romaji: "dou",    meaning: "moving",   themes: ["abstract"] },
  { kanji: "東", romaji: "higashi",meaning: "east",     themes: ["direction"] },
  { kanji: "西", romaji: "nishi",  meaning: "west",     themes: ["direction"] },
  { kanji: "南", romaji: "minami", meaning: "south",    themes: ["direction"] },
  { kanji: "北", romaji: "kita",   meaning: "north",    themes: ["direction"] },
  { kanji: "松", romaji: "matsu",  meaning: "pine",     themes: ["nature"] },
  { kanji: "竹", romaji: "take",   meaning: "bamboo",   themes: ["nature"] },
  { kanji: "梅", romaji: "ume",    meaning: "plum",     themes: ["nature", "spring"] },
  { kanji: "茶", romaji: "cha",    meaning: "tea",      themes: ["culture"] },
  { kanji: "禅", romaji: "zen",    meaning: "zen",      themes: ["culture"] },
  { kanji: "和", romaji: "wa",     meaning: "harmony",  themes: ["abstract"] },
  { kanji: "間", romaji: "ma",     meaning: "interval", themes: ["abstract"] },
  { kanji: "美", romaji: "bi",     meaning: "beauty",   themes: ["abstract"] },
  { kanji: "真", romaji: "shin",   meaning: "truth",    themes: ["abstract"] },
  { kanji: "誠", romaji: "makoto", meaning: "sincerity",themes: ["abstract"] },
  { kanji: "勇", romaji: "yuu",    meaning: "courage",  themes: ["abstract"] },
  { kanji: "希", romaji: "ki",     meaning: "hope",     themes: ["abstract"] },
  { kanji: "信", romaji: "shin",   meaning: "trust",    themes: ["abstract"] },
  { kanji: "知", romaji: "chi",    meaning: "knowing",  themes: ["abstract"] },
  { kanji: "学", romaji: "gaku",   meaning: "study",    themes: ["abstract"] },
  { kanji: "書", romaji: "sho",    meaning: "writing",  themes: ["culture"] },
  { kanji: "歌", romaji: "uta",    meaning: "song",     themes: ["culture"] },
  { kanji: "夢", romaji: "yume",   meaning: "dream",    themes: ["abstract"] },
  { kanji: "歩", romaji: "aru",    meaning: "walk",     themes: ["motion"] },

  // Numbers
  { kanji: "一", romaji: "ichi",   meaning: "one",      themes: ["number"] },
  { kanji: "二", romaji: "ni",     meaning: "two",      themes: ["number"] },
  { kanji: "三", romaji: "san",    meaning: "three",    themes: ["number"] },
  { kanji: "四", romaji: "shi",    meaning: "four",     themes: ["number"] },
  { kanji: "五", romaji: "go",     meaning: "five",     themes: ["number"] },
  { kanji: "六", romaji: "roku",   meaning: "six",      themes: ["number"] },
  { kanji: "七", romaji: "shichi", meaning: "seven",    themes: ["number"] },
  { kanji: "八", romaji: "hachi",  meaning: "eight",    themes: ["number"] },
  { kanji: "九", romaji: "kyuu",   meaning: "nine",     themes: ["number"] },
  { kanji: "十", romaji: "juu",    meaning: "ten",      themes: ["number"] },
  { kanji: "百", romaji: "hyaku",  meaning: "hundred",  themes: ["number"] },
  { kanji: "千", romaji: "sen",    meaning: "thousand", themes: ["number"] },
  { kanji: "万", romaji: "man",    meaning: "ten thousand", themes: ["number"] },
  { kanji: "半", romaji: "han",    meaning: "half",     themes: ["number"] },
  { kanji: "数", romaji: "kazu",   meaning: "count",    themes: ["number"] },

  // Time
  { kanji: "年", romaji: "nen",    meaning: "year",     themes: ["time"] },
  { kanji: "時", romaji: "toki",   meaning: "time",     themes: ["time"] },
  { kanji: "分", romaji: "fun",    meaning: "minute",   themes: ["time"] },
  { kanji: "秒", romaji: "byou",   meaning: "second",   themes: ["time"] },
  { kanji: "昼", romaji: "hiru",   meaning: "noon",     themes: ["time"] },
  { kanji: "晩", romaji: "ban",    meaning: "evening",  themes: ["time"] },
  { kanji: "暮", romaji: "kure",   meaning: "dusk",     themes: ["time"] },
  { kanji: "週", romaji: "shuu",   meaning: "week",     themes: ["time"] },
  { kanji: "末", romaji: "sue",    meaning: "end",      themes: ["time"] },
  { kanji: "始", romaji: "hajime", meaning: "beginning",themes: ["time"] },

  // People
  { kanji: "人", romaji: "hito",   meaning: "person",   themes: ["people"] },
  { kanji: "男", romaji: "otoko",  meaning: "man",      themes: ["people"] },
  { kanji: "女", romaji: "onna",   meaning: "woman",    themes: ["people"] },
  { kanji: "子", romaji: "ko",     meaning: "child",    themes: ["people"] },
  { kanji: "父", romaji: "chichi", meaning: "father",   themes: ["people"] },
  { kanji: "母", romaji: "haha",   meaning: "mother",   themes: ["people"] },
  { kanji: "兄", romaji: "ani",    meaning: "elder brother", themes: ["people"] },
  { kanji: "弟", romaji: "otouto", meaning: "younger brother", themes: ["people"] },
  { kanji: "姉", romaji: "ane",    meaning: "elder sister",   themes: ["people"] },
  { kanji: "妹", romaji: "imouto", meaning: "younger sister", themes: ["people"] },
  { kanji: "友", romaji: "tomo",   meaning: "friend",   themes: ["people"] },
  { kanji: "主", romaji: "nushi",  meaning: "host",     themes: ["people"] },
  { kanji: "君", romaji: "kimi",   meaning: "lord",     themes: ["people"] },
  { kanji: "客", romaji: "kyaku",  meaning: "guest",    themes: ["people"] },
  { kanji: "王", romaji: "ou",     meaning: "king",     themes: ["people"] },
  { kanji: "民", romaji: "tami",   meaning: "people",   themes: ["people"] },

  // Body
  { kanji: "目", romaji: "me",     meaning: "eye",      themes: ["body"] },
  { kanji: "耳", romaji: "mimi",   meaning: "ear",      themes: ["body"] },
  { kanji: "口", romaji: "kuchi",  meaning: "mouth",    themes: ["body"] },
  { kanji: "手", romaji: "te",     meaning: "hand",     themes: ["body"] },
  { kanji: "足", romaji: "ashi",   meaning: "foot",     themes: ["body"] },
  { kanji: "体", romaji: "karada", meaning: "body",     themes: ["body"] },
  { kanji: "顔", romaji: "kao",    meaning: "face",     themes: ["body"] },
  { kanji: "頭", romaji: "atama",  meaning: "head",     themes: ["body"] },
  { kanji: "髪", romaji: "kami",   meaning: "hair",     themes: ["body"] },
  { kanji: "歯", romaji: "ha",     meaning: "tooth",    themes: ["body"] },
  { kanji: "舌", romaji: "shita",  meaning: "tongue",   themes: ["body"] },
  { kanji: "喉", romaji: "nodo",   meaning: "throat",   themes: ["body"] },
  { kanji: "胸", romaji: "mune",   meaning: "chest",    themes: ["body"] },
  { kanji: "腹", romaji: "hara",   meaning: "belly",    themes: ["body"] },
  { kanji: "背", romaji: "senaka", meaning: "back",     themes: ["body"] },
  { kanji: "肩", romaji: "kata",   meaning: "shoulder", themes: ["body"] },
  { kanji: "腕", romaji: "ude",    meaning: "arm",      themes: ["body"] },
  { kanji: "指", romaji: "yubi",   meaning: "finger",   themes: ["body"] },
  { kanji: "膝", romaji: "hiza",   meaning: "knee",     themes: ["body"] },
  { kanji: "骨", romaji: "hone",   meaning: "bone",     themes: ["body"] },

  // Nature (extended)
  { kanji: "林", romaji: "hayashi",meaning: "grove",    themes: ["nature"] },
  { kanji: "森", romaji: "mori",   meaning: "forest",   themes: ["nature"] },
  { kanji: "田", romaji: "ta",     meaning: "rice field",themes: ["nature"] },
  { kanji: "畑", romaji: "hatake", meaning: "field",    themes: ["nature"] },
  { kanji: "池", romaji: "ike",    meaning: "pond",     themes: ["nature"] },
  { kanji: "湖", romaji: "mizuumi",meaning: "lake",     themes: ["nature"] },
  { kanji: "沼", romaji: "numa",   meaning: "marsh",    themes: ["nature"] },
  { kanji: "谷", romaji: "tani",   meaning: "valley",   themes: ["nature"] },
  { kanji: "岳", romaji: "take",   meaning: "peak",     themes: ["nature"] },
  { kanji: "岸", romaji: "kishi",  meaning: "shore",    themes: ["nature"] },
  { kanji: "浜", romaji: "hama",   meaning: "beach",    themes: ["nature"] },
  { kanji: "岡", romaji: "oka",    meaning: "hill",     themes: ["nature"] },
  { kanji: "峰", romaji: "mine",   meaning: "summit",   themes: ["nature"] },
  { kanji: "滝", romaji: "taki",   meaning: "waterfall",themes: ["nature"] },
  { kanji: "沢", romaji: "sawa",   meaning: "stream",   themes: ["nature"] },

  // Weather (extended)
  { kanji: "晴", romaji: "hare",   meaning: "clear sky",themes: ["weather"] },
  { kanji: "暑", romaji: "atsu",   meaning: "hot",      themes: ["weather", "summer"] },
  { kanji: "寒", romaji: "samu",   meaning: "cold",     themes: ["weather", "winter"] },
  { kanji: "涼", romaji: "suzu",   meaning: "cool",     themes: ["weather"] },
  { kanji: "暖", romaji: "atataka",meaning: "warm",     themes: ["weather"] },
  { kanji: "嵐", romaji: "arashi", meaning: "storm",    themes: ["weather"] },
  { kanji: "雷", romaji: "kaminari",meaning: "thunder", themes: ["weather"] },
  { kanji: "電", romaji: "den",    meaning: "lightning",themes: ["weather"] },
  { kanji: "霧", romaji: "kiri",   meaning: "mist",     themes: ["weather"] },
  { kanji: "霜", romaji: "shimo",  meaning: "frost",    themes: ["weather", "winter"] },

  // Animals
  { kanji: "馬", romaji: "uma",    meaning: "horse",    themes: ["animal"] },
  { kanji: "牛", romaji: "ushi",   meaning: "cow",      themes: ["animal"] },
  { kanji: "犬", romaji: "inu",    meaning: "dog",      themes: ["animal"] },
  { kanji: "猫", romaji: "neko",   meaning: "cat",      themes: ["animal"] },
  { kanji: "魚", romaji: "sakana", meaning: "fish",     themes: ["animal"] },
  { kanji: "虫", romaji: "mushi",  meaning: "insect",   themes: ["animal"] },
  { kanji: "蛇", romaji: "hebi",   meaning: "snake",    themes: ["animal"] },
  { kanji: "龍", romaji: "ryuu",   meaning: "dragon",   themes: ["animal", "myth"] },
  { kanji: "虎", romaji: "tora",   meaning: "tiger",    themes: ["animal"] },
  { kanji: "熊", romaji: "kuma",   meaning: "bear",     themes: ["animal"] },
  { kanji: "鯨", romaji: "kujira", meaning: "whale",    themes: ["animal"] },
  { kanji: "兎", romaji: "usagi",  meaning: "rabbit",   themes: ["animal"] },
  { kanji: "羊", romaji: "hitsuji",meaning: "sheep",    themes: ["animal"] },
  { kanji: "鶴", romaji: "tsuru",  meaning: "crane",    themes: ["animal"] },
  { kanji: "鷹", romaji: "taka",   meaning: "hawk",     themes: ["animal"] },
  { kanji: "蝶", romaji: "chou",   meaning: "butterfly",themes: ["animal"] },

  // Plants (extended)
  { kanji: "草", romaji: "kusa",   meaning: "grass",    themes: ["nature"] },
  { kanji: "桜", romaji: "sakura", meaning: "cherry blossom", themes: ["nature", "spring"] },
  { kanji: "紅", romaji: "beni",   meaning: "crimson",  themes: ["color"] },
  { kanji: "緑", romaji: "midori", meaning: "green",    themes: ["color", "nature"] },
  { kanji: "苔", romaji: "koke",   meaning: "moss",     themes: ["nature"] },
  { kanji: "蘭", romaji: "ran",    meaning: "orchid",   themes: ["nature"] },
  { kanji: "菊", romaji: "kiku",   meaning: "chrysanthemum", themes: ["nature", "autumn"] },
  { kanji: "萩", romaji: "hagi",   meaning: "bush clover", themes: ["nature", "autumn"] },
  { kanji: "椿", romaji: "tsubaki",meaning: "camellia", themes: ["nature"] },
  { kanji: "杉", romaji: "sugi",   meaning: "cedar",    themes: ["nature"] },

  // Colors (extended)
  { kanji: "黄", romaji: "ki",     meaning: "yellow",   themes: ["color"] },
  { kanji: "紫", romaji: "murasaki",meaning: "purple",  themes: ["color"] },
  { kanji: "銀", romaji: "gin",    meaning: "silver",   themes: ["color"] },
  { kanji: "朱", romaji: "shu",    meaning: "vermilion",themes: ["color"] },
  { kanji: "紺", romaji: "kon",    meaning: "navy",     themes: ["color"] },
  { kanji: "桃", romaji: "momo",   meaning: "peach",    themes: ["color"] },
  { kanji: "灰", romaji: "hai",    meaning: "gray",     themes: ["color"] },

  // Direction & space
  { kanji: "中", romaji: "naka",   meaning: "middle",   themes: ["direction"] },
  { kanji: "内", romaji: "uchi",   meaning: "inside",   themes: ["direction"] },
  { kanji: "外", romaji: "soto",   meaning: "outside",  themes: ["direction"] },
  { kanji: "上", romaji: "ue",     meaning: "above",    themes: ["direction"] },
  { kanji: "下", romaji: "shita",  meaning: "below",    themes: ["direction"] },
  { kanji: "左", romaji: "hidari", meaning: "left",     themes: ["direction"] },
  { kanji: "右", romaji: "migi",   meaning: "right",    themes: ["direction"] },
  { kanji: "表", romaji: "omote",  meaning: "front",    themes: ["direction"] },
  { kanji: "裏", romaji: "ura",    meaning: "back",     themes: ["direction"] },
  { kanji: "前", romaji: "mae",    meaning: "before",   themes: ["direction"] },
  { kanji: "後", romaji: "ato",    meaning: "after",    themes: ["direction"] },
  { kanji: "横", romaji: "yoko",   meaning: "side",     themes: ["direction"] },

  // Virtues / abstract
  { kanji: "理", romaji: "kotowari",meaning: "reason",  themes: ["abstract"] },
  { kanji: "義", romaji: "gi",     meaning: "justice",  themes: ["abstract"] },
  { kanji: "礼", romaji: "rei",    meaning: "courtesy", themes: ["abstract"] },
  { kanji: "智", romaji: "chi",    meaning: "wisdom",   themes: ["abstract"] },
  { kanji: "忠", romaji: "chuu",   meaning: "loyalty",  themes: ["abstract"] },
  { kanji: "孝", romaji: "kou",    meaning: "filial",   themes: ["abstract"] },
  { kanji: "愛", romaji: "ai",     meaning: "love",     themes: ["abstract"] },
  { kanji: "慈", romaji: "ji",     meaning: "compassion",themes: ["abstract"] },
  { kanji: "寛", romaji: "kan",    meaning: "tolerance",themes: ["abstract"] },
  { kanji: "善", romaji: "zen",    meaning: "good",     themes: ["abstract"] },
  { kanji: "賢", romaji: "ken",    meaning: "clever",   themes: ["abstract"] },
  { kanji: "才", romaji: "sai",    meaning: "talent",   themes: ["abstract"] },
  { kanji: "巧", romaji: "takumi", meaning: "skill",    themes: ["abstract"] },
  { kanji: "望", romaji: "nozomi", meaning: "wish",     themes: ["abstract"] },
  { kanji: "福", romaji: "fuku",   meaning: "fortune",  themes: ["abstract"] },
  { kanji: "徳", romaji: "toku",   meaning: "virtue",   themes: ["abstract"] },

  // Light & dark
  { kanji: "暗", romaji: "kura",   meaning: "dark",     themes: ["abstract"] },
  { kanji: "明", romaji: "mei",    meaning: "bright",   themes: ["abstract"] },
  { kanji: "闇", romaji: "yami",   meaning: "gloom",    themes: ["abstract"] },
  { kanji: "灯", romaji: "tomoshi",meaning: "lamp",     themes: ["object"] },
  { kanji: "炎", romaji: "honoo",  meaning: "flame",    themes: ["element"] },

  // Time-passing
  { kanji: "今", romaji: "ima",    meaning: "now",      themes: ["time"] },
  { kanji: "昔", romaji: "mukashi",meaning: "long ago", themes: ["time"] },
  { kanji: "永", romaji: "ei",     meaning: "eternal",  themes: ["time"] },
  { kanji: "久", romaji: "hisa",   meaning: "enduring", themes: ["time"] },
  { kanji: "短", romaji: "mijika", meaning: "short",    themes: ["abstract"] },
  { kanji: "長", romaji: "naga",   meaning: "long",     themes: ["abstract"] },
  { kanji: "旧", romaji: "kyuu",   meaning: "old days", themes: ["time"] },
  { kanji: "老", romaji: "oi",     meaning: "aged",     themes: ["abstract"] },

  // Cosmos
  { kanji: "宇", romaji: "u",      meaning: "universe", themes: ["cosmos"] },
  { kanji: "宙", romaji: "chuu",   meaning: "cosmos",   themes: ["cosmos"] },
  { kanji: "天", romaji: "ten",    meaning: "heaven",   themes: ["cosmos"] },
  { kanji: "地", romaji: "chi",    meaning: "earth",    themes: ["cosmos"] },
  { kanji: "河", romaji: "kawa",   meaning: "great river", themes: ["nature"] },
  { kanji: "潮", romaji: "shio",   meaning: "tide",     themes: ["nature"] },
  { kanji: "波", romaji: "nami",   meaning: "wave",     themes: ["nature"] },
  { kanji: "季", romaji: "ki",     meaning: "season",   themes: ["time"] },
  { kanji: "暦", romaji: "koyomi", meaning: "calendar", themes: ["time"] },

  // Movement
  { kanji: "走", romaji: "hashi",  meaning: "run",      themes: ["motion"] },
  { kanji: "飛", romaji: "tobi",   meaning: "fly",      themes: ["motion"] },
  { kanji: "泳", romaji: "oyo",    meaning: "swim",     themes: ["motion"] },
  { kanji: "立", romaji: "tachi",  meaning: "stand",    themes: ["motion"] },
  { kanji: "座", romaji: "suwa",   meaning: "sit",      themes: ["motion"] },
  { kanji: "行", romaji: "iku",    meaning: "go",       themes: ["motion"] },
  { kanji: "来", romaji: "ku",     meaning: "come",     themes: ["motion"] },
  { kanji: "帰", romaji: "kaeri",  meaning: "return",   themes: ["motion"] },
  { kanji: "進", romaji: "susumi", meaning: "advance",  themes: ["motion"] },
  { kanji: "退", romaji: "shirizo",meaning: "retreat",  themes: ["motion"] },
  { kanji: "出", romaji: "deru",   meaning: "exit",     themes: ["motion"] },
  { kanji: "入", romaji: "iru",    meaning: "enter",    themes: ["motion"] },
  { kanji: "開", romaji: "hiraki", meaning: "open",     themes: ["motion"] },
  { kanji: "閉", romaji: "toji",   meaning: "close",    themes: ["motion"] },
  { kanji: "止", romaji: "yamu",   meaning: "cease",    themes: ["motion"] },

  // Sound & feeling
  { kanji: "鳴", romaji: "naki",   meaning: "cry out",  themes: ["abstract"] },
  { kanji: "響", romaji: "hibiki", meaning: "echo",     themes: ["abstract"] },
  { kanji: "笑", romaji: "emi",    meaning: "smile",    themes: ["feeling"] },
  { kanji: "泣", romaji: "naki",   meaning: "weep",     themes: ["feeling"] },
  { kanji: "怒", romaji: "ika",    meaning: "anger",    themes: ["feeling"] },
  { kanji: "悲", romaji: "kana",   meaning: "sad",      themes: ["feeling"] },
  { kanji: "楽", romaji: "raku",   meaning: "ease",     themes: ["feeling"] },
  { kanji: "苦", romaji: "kuru",   meaning: "bitter",   themes: ["feeling"] },
  { kanji: "痛", romaji: "ita",    meaning: "pain",     themes: ["feeling"] },
  { kanji: "安", romaji: "yasu",   meaning: "peace",    themes: ["abstract"] },
  { kanji: "平", romaji: "hei",    meaning: "level",    themes: ["abstract"] },
  { kanji: "喜", romaji: "yorokobi",meaning: "joy",     themes: ["feeling"] },

  // Buildings
  { kanji: "家", romaji: "ie",     meaning: "house",    themes: ["building"] },
  { kanji: "屋", romaji: "ya",     meaning: "roof",     themes: ["building"] },
  { kanji: "城", romaji: "shiro",  meaning: "castle",   themes: ["building"] },
  { kanji: "館", romaji: "yakata", meaning: "hall",     themes: ["building"] },
  { kanji: "寺", romaji: "tera",   meaning: "temple",   themes: ["building"] },
  { kanji: "社", romaji: "yashiro",meaning: "shrine",   themes: ["building"] },
  { kanji: "門", romaji: "mon",    meaning: "gate",     themes: ["building"] },
  { kanji: "橋", romaji: "hashi",  meaning: "bridge",   themes: ["building"] },
  { kanji: "庭", romaji: "niwa",   meaning: "garden",   themes: ["building"] },
  { kanji: "街", romaji: "machi",  meaning: "street",   themes: ["building"] },
  { kanji: "路", romaji: "ro",     meaning: "road",     themes: ["building"] },
  { kanji: "駅", romaji: "eki",    meaning: "station",  themes: ["building"] },
  { kanji: "港", romaji: "minato", meaning: "harbor",   themes: ["building"] },
  { kanji: "塔", romaji: "tou",    meaning: "tower",    themes: ["building"] },
  { kanji: "階", romaji: "kai",    meaning: "floor",    themes: ["building"] },

  // Tools
  { kanji: "筆", romaji: "fude",   meaning: "brush",    themes: ["object"] },
  { kanji: "墨", romaji: "sumi",   meaning: "ink",      themes: ["object"] },
  { kanji: "紙", romaji: "kami",   meaning: "paper",    themes: ["object"] },
  { kanji: "本", romaji: "hon",    meaning: "book",     themes: ["object"] },
  { kanji: "刀", romaji: "katana", meaning: "sword",    themes: ["object"] },
  { kanji: "剣", romaji: "ken",    meaning: "blade",    themes: ["object"] },
  { kanji: "弓", romaji: "yumi",   meaning: "bow",      themes: ["object"] },
  { kanji: "矢", romaji: "ya",     meaning: "arrow",    themes: ["object"] },
  { kanji: "鏡", romaji: "kagami", meaning: "mirror",   themes: ["object"] },
  { kanji: "鐘", romaji: "shou",   meaning: "bell",     themes: ["object"] },

  // Crafts & culture
  { kanji: "武", romaji: "bu",     meaning: "martial",  themes: ["culture"] },
  { kanji: "詩", romaji: "shi",    meaning: "poem",     themes: ["culture"] },
  { kanji: "唱", romaji: "shou",   meaning: "chant",    themes: ["culture"] },
  { kanji: "玉", romaji: "tama",   meaning: "jewel",    themes: ["object"] },
  { kanji: "鈴", romaji: "suzu",   meaning: "small bell", themes: ["object"] },
  { kanji: "杯", romaji: "sakazuki",meaning: "cup",     themes: ["object"] },
  { kanji: "帆", romaji: "ho",     meaning: "sail",     themes: ["object"] },
  { kanji: "船", romaji: "fune",   meaning: "boat",     themes: ["object"] },
  { kanji: "車", romaji: "kuruma", meaning: "vehicle",  themes: ["object"] },
  { kanji: "舞", romaji: "mai",    meaning: "dance",    themes: ["culture"] },

  // Quantity & quality
  { kanji: "多", romaji: "oo",     meaning: "many",     themes: ["abstract"] },
  { kanji: "少", romaji: "suko",   meaning: "few",      themes: ["abstract"] },
  { kanji: "重", romaji: "omo",    meaning: "heavy",    themes: ["abstract"] },
  { kanji: "軽", romaji: "karu",   meaning: "light weight", themes: ["abstract"] },
  { kanji: "早", romaji: "haya",   meaning: "early",    themes: ["abstract"] },
  { kanji: "速", romaji: "soku",   meaning: "fast",     themes: ["abstract"] },
  { kanji: "遅", romaji: "oso",    meaning: "slow",     themes: ["abstract"] },
  { kanji: "強", romaji: "tsuyo",  meaning: "strong",   themes: ["abstract"] },
  { kanji: "弱", romaji: "yowa",   meaning: "weak",     themes: ["abstract"] },
  { kanji: "大", romaji: "dai",    meaning: "big",      themes: ["abstract"] },
  { kanji: "小", romaji: "sho",    meaning: "small",    themes: ["abstract"] },

  // Concepts & spirit
  { kanji: "神", romaji: "kami",   meaning: "god",      themes: ["spirit"] },
  { kanji: "仏", romaji: "hotoke", meaning: "buddha",   themes: ["spirit"] },
  { kanji: "霊", romaji: "rei",    meaning: "spirit",   themes: ["spirit"] },
  { kanji: "魂", romaji: "tamashii",meaning: "soul",    themes: ["spirit"] },
  { kanji: "縁", romaji: "en",     meaning: "bond",     themes: ["abstract"] },
  { kanji: "色", romaji: "iro",    meaning: "color",    themes: ["abstract"] },
  { kanji: "形", romaji: "katachi",meaning: "shape",    themes: ["abstract"] },
  { kanji: "質", romaji: "shitsu", meaning: "quality",  themes: ["abstract"] },
  { kanji: "量", romaji: "ryou",   meaning: "quantity", themes: ["abstract"] },
  { kanji: "命", romaji: "inochi", meaning: "life",     themes: ["abstract"] },

  // State verbs
  { kanji: "眠", romaji: "nemu",   meaning: "sleep",    themes: ["state"] },
  { kanji: "起", romaji: "oki",    meaning: "rise",     themes: ["state"] },
  { kanji: "寝", romaji: "ne",     meaning: "lie down", themes: ["state"] },
  { kanji: "食", romaji: "shoku",  meaning: "eat",      themes: ["state"] },
  { kanji: "飲", romaji: "nomi",   meaning: "drink",    themes: ["state"] },
  { kanji: "居", romaji: "i",      meaning: "dwell",    themes: ["state"] },
  { kanji: "住", romaji: "ju",     meaning: "reside",   themes: ["state"] },
  { kanji: "過", romaji: "sugi",   meaning: "pass",     themes: ["state"] },
  { kanji: "思", romaji: "omoi",   meaning: "think",    themes: ["state"] },
  { kanji: "想", romaji: "sou",    meaning: "imagine",  themes: ["state"] },

  // Work & education
  { kanji: "教", romaji: "oshi",   meaning: "teach",    themes: ["work"] },
  { kanji: "業", romaji: "gyou",   meaning: "work",     themes: ["work"] },
  { kanji: "職", romaji: "shoku",  meaning: "trade",    themes: ["work"] },
  { kanji: "仕", romaji: "shi",    meaning: "service",  themes: ["work"] },
  { kanji: "営", romaji: "ei",     meaning: "manage",   themes: ["work"] },
  { kanji: "究", romaji: "kyuu",   meaning: "inquire",  themes: ["work"] },
  { kanji: "試", romaji: "kokoromi",meaning: "test",    themes: ["work"] },
  { kanji: "案", romaji: "an",     meaning: "plan",     themes: ["work"] },
  { kanji: "寿", romaji: "kotobuki",meaning: "longevity",themes: ["abstract"] },
  { kanji: "産", romaji: "san",    meaning: "produce",  themes: ["work"] },

  // Culture & aesthetic
  { kanji: "俳", romaji: "hai",    meaning: "haiku",    themes: ["culture"] },
  { kanji: "句", romaji: "ku",     meaning: "verse",    themes: ["culture"] },
  { kanji: "雅", romaji: "ga",     meaning: "elegance", themes: ["culture"] },
  { kanji: "忍", romaji: "shinobu",meaning: "endure",   themes: ["abstract"] },
  { kanji: "侘", romaji: "wabi",   meaning: "humility", themes: ["culture"] },
  { kanji: "寂", romaji: "sabi",   meaning: "solitude", themes: ["culture"] },
  { kanji: "粋", romaji: "iki",    meaning: "chic",     themes: ["culture"] },
  { kanji: "渋", romaji: "shibu",  meaning: "subdued",  themes: ["culture"] },
  { kanji: "趣", romaji: "omomu",  meaning: "charm",    themes: ["culture"] },

  // More animals
  { kanji: "鯉", romaji: "koi",    meaning: "carp",     themes: ["animal"] },
  { kanji: "蛙", romaji: "kaeru",  meaning: "frog",     themes: ["animal"] },
  { kanji: "蜂", romaji: "hachi",  meaning: "bee",      themes: ["animal"] },
  { kanji: "蛍", romaji: "hotaru", meaning: "firefly",  themes: ["animal"] },
  { kanji: "蟹", romaji: "kani",   meaning: "crab",     themes: ["animal"] },
  { kanji: "燕", romaji: "tsubame",meaning: "swallow",  themes: ["animal"] },
  { kanji: "鳩", romaji: "hato",   meaning: "dove",     themes: ["animal"] },
  { kanji: "鴨", romaji: "kamo",   meaning: "duck",     themes: ["animal"] },

  // Food & taste
  { kanji: "米", romaji: "kome",   meaning: "rice",     themes: ["food"] },
  { kanji: "麦", romaji: "mugi",   meaning: "wheat",    themes: ["food"] },
  { kanji: "豆", romaji: "mame",   meaning: "bean",     themes: ["food"] },
  { kanji: "塩", romaji: "shio",   meaning: "salt",     themes: ["food"] },
  { kanji: "酒", romaji: "sake",   meaning: "rice wine",themes: ["food"] },
  { kanji: "味", romaji: "aji",    meaning: "taste",    themes: ["food"] },
  { kanji: "香", romaji: "kao",    meaning: "fragrance",themes: ["food"] },
  { kanji: "蜜", romaji: "mitsu",  meaning: "honey",    themes: ["food"] },

  // More verbs
  { kanji: "持", romaji: "mochi",  meaning: "hold",     themes: ["motion"] },
  { kanji: "取", romaji: "tori",   meaning: "take",     themes: ["motion"] },
  { kanji: "受", romaji: "uke",    meaning: "receive",  themes: ["motion"] },
  { kanji: "送", romaji: "oku",    meaning: "send",     themes: ["motion"] },
  { kanji: "与", romaji: "atae",   meaning: "give",     themes: ["motion"] },
  { kanji: "貸", romaji: "kashi",  meaning: "lend",     themes: ["motion"] },
  { kanji: "借", romaji: "kari",   meaning: "borrow",   themes: ["motion"] },
  { kanji: "求", romaji: "motome", meaning: "seek",     themes: ["motion"] },
  { kanji: "探", romaji: "saga",   meaning: "search",   themes: ["motion"] },
  { kanji: "守", romaji: "mamo",   meaning: "protect",  themes: ["motion"] },
  { kanji: "助", romaji: "tasuke", meaning: "help",     themes: ["motion"] },
  { kanji: "待", romaji: "machi",  meaning: "wait",     themes: ["motion"] },

  // Abstract / language
  { kanji: "法", romaji: "hou",    meaning: "law",      themes: ["abstract"] },
  { kanji: "術", romaji: "jutsu",  meaning: "art",      themes: ["abstract"] },
  { kanji: "技", romaji: "waza",   meaning: "technique",themes: ["abstract"] },
  { kanji: "芸", romaji: "gei",    meaning: "skill",    themes: ["culture"] },
  { kanji: "文", romaji: "bun",    meaning: "writing",  themes: ["culture"] },
  { kanji: "字", romaji: "ji",     meaning: "character",themes: ["culture"] },
  { kanji: "言", romaji: "koto",   meaning: "word",     themes: ["culture"] },
  { kanji: "語", romaji: "go",     meaning: "language", themes: ["culture"] },
  { kanji: "議", romaji: "gi",     meaning: "deliberation",themes: ["abstract"] },
  { kanji: "答", romaji: "kotae",  meaning: "answer",   themes: ["abstract"] },

  // Metals
  { kanji: "鉄", romaji: "tetsu",  meaning: "iron",     themes: ["element"] },
  { kanji: "銅", romaji: "dou",    meaning: "copper",   themes: ["element"] },
  { kanji: "鉛", romaji: "namari", meaning: "lead",     themes: ["element"] },

  // Geography
  { kanji: "国", romaji: "kuni",   meaning: "country",  themes: ["place"] },
  { kanji: "都", romaji: "miyako", meaning: "capital",  themes: ["place"] },
  { kanji: "県", romaji: "ken",    meaning: "prefecture",themes: ["place"] },
  { kanji: "市", romaji: "shi",    meaning: "city",     themes: ["place"] },
  { kanji: "村", romaji: "mura",   meaning: "village",  themes: ["place"] },
  { kanji: "郡", romaji: "gun",    meaning: "district", themes: ["place"] },
  { kanji: "京", romaji: "kyou",   meaning: "capital city", themes: ["place"] },
  { kanji: "区", romaji: "ku",     meaning: "ward",     themes: ["place"] },
];

/** Reserved fixtures for special calendar dates. */
export const RESERVED: { monthDay: string; entry: KanjiEntry }[] = [
  { monthDay: "01-01", entry: { kanji: "元", romaji: "gen",     meaning: "origin",      themes: ["new-year"] } },
  { monthDay: "03-20", entry: { kanji: "春", romaji: "haru",    meaning: "spring",      themes: ["season"] } },
  { monthDay: "06-21", entry: { kanji: "夏", romaji: "natsu",   meaning: "summer",      themes: ["season"] } },
  { monthDay: "09-22", entry: { kanji: "秋", romaji: "aki",     meaning: "autumn",      themes: ["season"] } },
  { monthDay: "12-21", entry: { kanji: "冬", romaji: "fuyu",    meaning: "winter",      themes: ["season"] } },
];

export function findReserved(date: string): KanjiEntry | null {
  const md = date.slice(5); // 'MM-DD'
  return RESERVED.find((r) => r.monthDay === md)?.entry ?? null;
}
